sudo: false
language: go

go:
  - 1.4
  - tip

before_install:
  - go install -race std

  # linting
  - go get github.com/golang/lint
  - go install github.com/golang/lint/golint

  # code coverage
  - go get golang.org/x/tools/cmd/...
  - go get github.com/modocache/gover
  - if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then go get github.com/mattn/goveralls; fi

  # get the dependencies etc
  - go get github.com/tools/godep
  - go get github.com/jteeuwen/go-bindata
  - godep restore

script: 
  - go generate ./...
  - golint ./...
  - godep go test -v -race ./...
  - godep go test -covermode=count -coverprofile=swagger.coverprofile .
  - godep go test -covermode=count -coverprofile=reflection.coverprofile ./reflection
  - godep go test -covermode=count -coverprofile=swagger-serve.coverprofile ./swagger
  - gover
  - if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN; fi

env:
  secure: "BVU08Ozu3y4JRVeaaRV0h0Px3u2PpOdchykHfJX0+AeOQZO6mmE69JfCJFOkynBVOY9P3AerDPlrVHPK3eBAeEwX+XgKaFenE4n7LgvH1rlrjOngaPte76x5BdbiGkJ///L0cKJw1t6FQlPnqFpjckbmr9f6w9ItR8ClqR0vMEs="
