language: go

go:
  - 1.3

before_install:
  - go install -race std
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/tools/godep
  - export PATH=$HOME/gopath/bin:$PATH
  - make setup

script: 
  - make travis
