language: go

go:
  - 1.3

before_install:
  - echo $(env)
  - go install -race std
  - go get github.com/tools/godep

  # linting
  - go get github.com/golang/lint
  - go install github.com/golang/lint/golint

  # code coverage
  - go get code.google.com/p/go.tools/cmd/cover
  - if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then go get github.com/mattn/goveralls; fi

  - godep restore

script: 
  - golint ./...
  - godep go test -v -race ./...
  - godep go test -coverprofile=swagger.coverprofile .
  - godep go test -coverprofile=reflection.coverprofile ./reflection
  - if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN; fi

env:
  secure: "BVU08Ozu3y4JRVeaaRV0h0Px3u2PpOdchykHfJX0+AeOQZO6mmE69JfCJFOkynBVOY9P3AerDPlrVHPK3eBAeEwX+XgKaFenE4n7LgvH1rlrjOngaPte76x5BdbiGkJ///L0cKJw1t6FQlPnqFpjckbmr9f6w9ItR8ClqR0vMEs="
