version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: C:\gopath\src\github.com\go-swagger\go-swagger
shallow_clone: true # for startup speed

environment:
  GOPATH: C:\gopath
  GO15VENDOREXPERIMENT: 1
  GOCOVMODE: "mode: count"
  PATH: C:\gopath\bin;%PATH%

platform:
  - x64

# http://www.appveyor.com/docs/installed-software
install:
  # pre-installed MinGW at C:\MinGW is 32bit only
  # but MSYS2 at C:\msys64 has mingw64
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - gcc --version
  - g++ --version

  # need bzr for several tests
  - choco install bzr
  - set PATH=C:\Program Files (x86)\Bazaar;%PATH%
  - bzr --version

  # install go tools
  - go get -u -v golang.org/x/tools/cmd/goimports
  - go get -u -v golang.org/x/tools/cmd/cover
  - go get -u -v golang.org/x/tools/cmd/vet
  - go get -u -v golang.org/x/tools/cmd/stringer
  - go get -u -v golang.org/x/tools/cmd/gotype
  - go get -u -v golang.org/x/tools/cmd/godoc

  # code coverage
  - go get github.com/axw/gocov/gocov
  - go get gopkg.in/matm/v1/gocov-html

  # test output
  - go get -t -v -u -f github.com/cee-dub/go-junit-report

  # get the dependencies etc
  - go get github.com/tools/godep
  - go get github.com/jteeuwen/go-bindata/...

  # some helpful output for debugging builds
  - go version
  - go env


build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo %PATH%
  - echo %GOPATH%

test_script:
  - go test -v ./...

#artifacts:
#  - path: '%GOPATH%\bin\*.exe'
deploy: off
