version: 2
jobs:
  build:
    working_directory: /go/src/github.com/go-swagger/go-swagger
    docker:
      - image: goswagger/go-swagger:ci
    steps:
      - checkout
      
      - run: 
          name: Run the build
          command: ./hack/build-docker.sh
          no_output_timeout: 30m
      
      - run:
          name: Submit coverage results
          command: bash <(curl -s https://codecov.io/bash)
      
      - setup_remote_docker

      - deploy:
          command: |
            if echo $CIRCLE_TAG | grep -q -E "[0-9]+(\\.[0-9]+)*"; then
              ./hack/deploy.sh
            fi
      
      - deploy:
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              mkdir -p dist

              docker run --rm -it \
                -v `pwd`:/go/src/github.com/go-swagger/go-swagger \
                -w /go/src/github.com/go-swagger/go-swagger \
                golang:1.8-alpine \
                go build -o ./dist/swagger-musl  -a -tags netgo -installsuffix netgo ./cmd/swagger

              mkdir -p dockerbuild
              cp ./dist/swagger-musl Dockerfile ./dockerbuild
              
              docker build --pull -t quay.io/goswagger/swagger:dev ./dockerbuild
              docker login -u $API_USERNAME -p $QUAY_PASS -e $API_EMAIL https://quay.io
              docker push quay.io/goswagger/swagger
            fi
      
      - store_artifacts:
          path: /usr/share/dist
      
      - store_test_results:
          path: /usr/share/testresults